image: node

stages:
  - lint
  - unitTest

variables:
  PORT: 443

eslint:
  stage: lint
  before_script:
    - npm run autoinstall
  script:
    - npm run lintjs

csslint:
  stage: lint
  before_script:
    - npm run autoinstall
  script:
    - npm run lintcss

htmllint:
  stage: lint
  before_script:
    - npm run autoinstall
  script:
    - npm run linthtml

jest:
  stage: unitTest
  before_script:
    - npm run autoinstall
  script:
    - npm run unitTest
