# variables d'environnement
# variables:
#   NOM: VALUE

image: node

stages:
  - lint
  - unitTest
#   - exec

variables:
  PORT: 8080

eslint:
  stage: lint
  before_script:
    - npm install eslint --save-dev
    - npm install eslint-config-standard --save-dev
    - npm install eslint-plugin-import --save-dev
    - npm install eslint-plugin-node --save-dev
    - npm install eslint-plugin-promise --save-dev
    - npm install eslint-plugin-standard --save-dev
  script:
    - ./node_modules/.bin/eslint ./

csslint:
  stage: lint
  before_script:
    - npm install stylelint --save-dev
    - npm install stylelint-config-recommended --save-dev
  script:
    - ./node_modules/.bin/stylelint **/*.css
  allow_failure: true

jest:
  stage: unitTest
  before_script:
    - npm i
  script:
    - node test/unitTest.js

# server:
#   stage: exec
#   before_script:
#     - npm i
#   script:
#     - npm run start