# variables d'environnement
# variables:
#   NOM: VALUE

image: node

stages:
  - lint
  - unitTest
#   - exec

variables:
  PORT: 8080

eslint:
  stage: lint
  before_script:
    - npm install eslint --save-dev
    - npm install eslint-config-standard --save-dev
    - npm install eslint-plugin-import --save-dev
    - npm install eslint-plugin-node --save-dev
    - npm install eslint-plugin-promise --save-dev
    - npm install eslint-plugin-standard --save-dev
  script:
    - npm run lintjs

csslint:
  stage: lint
  before_script:
    - npm install stylelint --save-dev
    - npm install stylelint-config-recommended --save-dev
  script:
    - npm run lintcss

htmllint:
  stage: lint
  before_script:
    - npm install html-linter --save-dev
  script:
    - npm run linthtml

jest:
  stage: unitTest
  before_script:
    - npm i
  script:
    - npm run unitTest

# server:
#   stage: exec
#   before_script:
#     - npm i
#   script:
#     - npm run start