apiVersion: v1
kind: PersistentVolume
metadata:
  name: algolov_nodejs_volume
  namespace: algolov
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/home/algolov/admin/features_files"
    type: DirectoryOrCreate