apiVersion: apps/v1
kind: Deployment
metadata:
  name: algolov-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algolov-nodejs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: algolov-nodejs
    spec:
      containers:
        - image: ulysseguyon/algolov-server:latest
          imagePullPolicy: Always
          name: algolov-nodejs
          ports:
            - containerPort: 443
          env:
            - name: MONGO_INITDB_HOST
              valueFrom:
                configMapKeyRef:
                  name: algolov-config
                  key: MONGO_INITDB_HOST
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: algolov-config
                  key: MONGO_INITDB_DATABASE
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: algolov-config
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: algolov-config
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: nodejs-persistent-storage
              mountPath: /usr/src/app/admin/features_files
            # add - name
            #   and mountPath
            # for each persistent dir
        - image: mongo:4.2
          name: algolov-mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: algolov-config
                  key: MONGO_INITDB_DATABASE
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: algolov-config
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: algolov-config
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      # initContainers:
      #   - name: init-mongo
      #     image: busybox
      #     command: ['sh', '-c', 'until nslookup algolov-mongo; do echo waiting for algolov-mongo; sleep 2; done;']
      volumes:
        - name: nodejs-persistent-storage
          persistentVolumeClaim:
            claimName: algolov-nodejs-pv-claim
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: algolov-mongo-pv-claim
      dnsPolicy: Default
        # same