apiVersion: v1
kind: PersistentVolume
metadata:
  name: algolov-mongo-volume
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ulysse/Documents/algolov/data"
    type: DirectoryOrCreate