apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algolov-nodejs-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  selector: 
    matchLabels:
      storageKind: server-file