apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algolov_mongo_pv_claim
  namespace: algolov
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi