apiVersion: v1
kind: Service
metadata:
  name: algolov_mongo_port_service
  namespace: algolov
spec:
  ports:
    - name: mongo_tcp
      # service port in cluster
      port: 27017
      # port to contact inside container
      targetPort: 27017
  selector:
    app: algolov_mongo
  type: ClusterIP