# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: algolov-mongo
# spec:
#   selector:
#     matchLabels:
#       app: algolov-mongo
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: algolov-mongo
#     spec:
#       containers:
#         # by default, the image is pulled from docker hub
#         - image: mongo:4.2
#           name: algolov-mongo
#           ports:
#             - containerPort: 27017
#           env:
#             - name: MONGO_INITDB_DATABASE
#               valueFrom:
#                 configMapKeyRef:
#                   name: algolov-config
#                   key: MONGO_INITDB_DATABASE
#             - name: MONGO_INITDB_ROOT_USERNAME
#               valueFrom:
#                 configMapKeyRef:
#                   name: algolov-config
#                   key: MONGO_INITDB_ROOT_USERNAME
#             - name: MONGO_INITDB_ROOT_PASSWORD
#               valueFrom:
#                 configMapKeyRef:
#                   name: algolov-config
#                   key: MONGO_INITDB_ROOT_PASSWORD
#           volumeMounts:
#             - name: mongo-persistent-storage
#               mountPath: /data/db
#           # livenessProbe:
#           #   exec:
#           #     command: ["mongo", "--eval", "\"db.adminCommand('ping')\""]
#           #   initialDelaySeconds: 30
#           #   periodSeconds: 10
#           #   timeoutSeconds: 5
#       volumes:
#           - name: mongo-persistent-storage
#             persistentVolumeClaim:
#               claimName: algolov-mongo-pv-claim
#       dnsPolicy: Default