apiVersion: v1
kind: PersistentVolume
metadata:
  name: algolov-nodejs-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ulysse/Documents/algolov/admin/features_files"
    type: DirectoryOrCreate