apiVersion: v1
kind: PersistentVolume
metadata:
  name: algolov_mongo_volume
  namespace: algolov
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate